# Intro to Scikit Learn 

This is notebook for some useful function, testing, etc. Basically my sandbox
Mostly reviewing CPSC 340 materials 

0. End to end workflow on scikit-learn
1. Getting data ready
2. Chooising the right algo 
3. Fit model/algo  and make prediction
4. Evalu the model
5. Improve on a model
6. Save and train
7. Putting everything together

In [12]:
# getting data ready

import pandas as pd
import numpy as np
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [13]:
# create x (features matrix)

X = heart_disease.drop("target", axis=1)

# create y labels
y = heart_disease["target"]

In [14]:
# choosing the right model and hyperpara

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [15]:
# 3 fit the model to the data

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [16]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [17]:
# make prediction

y_label = clf.predict(np.array([0,2,3,4]))


ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [20]:
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
103   42    1   2       120   240    1        1      194      0      0.8   
136   60    0   2       120   178    1        1       96      0      0.0   
164   38    1   2       138   175    0        1      173      0      0.0   
141   43    1   0       115   303    0        1      181      0      1.2   
124   39    0   2        94   199    0        1      179      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
201   60    1   0       125   258    0        0      141      1      2.8   
168   63    1   0       130   254    0        0      147      0      1.4   
185   44    1   0       112   290    0        0      153      0      0.0   
35    46    0   2       142   177    0        0      160      1      1.4   
129   74    0   1       120   269    0        0      121      1      0.2   

     slope  ca  thal  
103      0   0     3  
136      2   0     2  
164      2   4     2  
141      1   0     2  
124      2   0     2  
..     ...  ..   ...  
201      1   1     3  
168      1   1     3  
185      2   1     2  
35       0   0     2  
129      2   1     2  

[242 rows x 13 columns]

In [21]:
y_preds = clf.predict(X_test)
y_preds

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1])

In [22]:
# 4 Evalu the mode on the training data and test data

clf.score(X_train, y_train)

1.0

In [23]:
clf.score(X_test, y_test)
# .8% accuracy 

0.8524590163934426

In [24]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

# compare test 

              precision    recall  f1-score   support

           0       0.77      0.87      0.82        23
           1       0.91      0.84      0.88        38

    accuracy                           0.85        61
   macro avg       0.84      0.86      0.85        61
weighted avg       0.86      0.85      0.85        61



In [25]:
confusion_matrix(y_test, y_preds)


array([[20,  3],
       [ 6, 32]])

In [26]:
accuracy_score(y_test, y_preds)

0.8524590163934426

In [27]:
# Improve a model 
# Try different amount of n_estimators

np.random.seed(99)
for i in range(10, 100, 10):
    print(f"Trying mode with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model on accuracy on test set: {clf.score(X_test, y_test) * 100:.2f}%")
    print('')

Trying mode with 10 estimators...
Model on accuracy on test set: 80.33%

Trying mode with 20 estimators...
Model on accuracy on test set: 83.61%

Trying mode with 30 estimators...
Model on accuracy on test set: 86.89%

Trying mode with 40 estimators...
Model on accuracy on test set: 85.25%

Trying mode with 50 estimators...
Model on accuracy on test set: 83.61%

Trying mode with 60 estimators...
Model on accuracy on test set: 86.89%

Trying mode with 70 estimators...
Model on accuracy on test set: 85.25%

Trying mode with 80 estimators...
Model on accuracy on test set: 85.25%

Trying mode with 90 estimators...
Model on accuracy on test set: 83.61%



In [28]:
# 6. save the model and load it

import pickle

pickle.dump(clf, open("random_forest_model_1.pkl", "wb"))

In [29]:
load_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
load_model.score(X_test, y_test)

0.8360655737704918

In [30]:
import sklearn
sklearn.show_versions()


System:
    python: 3.8.5 (default, Sep  4 2020, 02:22:02)  [Clang 10.0.0 ]
executable: /opt/anaconda3/bin/python
   machine: macOS-10.15.7-x86_64-i386-64bit

Python dependencies:
          pip: 20.2.4
   setuptools: 50.3.1.post20201107
      sklearn: 0.23.2
        numpy: 1.19.2
        scipy: 1.5.2
       Cython: 0.29.21
       pandas: 1.1.3
   matplotlib: 3.3.2
       joblib: 0.17.0
threadpoolctl: 2.1.0

Built with OpenMP: True


## 1. Getting data ready to be used with Machine Learning

1. Split the data into features and labels 
2. Filling or disregarding missing value (clean up on csv)
3. Converting non numerical values to numerical value (feature encoding)



In [31]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [32]:
X = heart_disease.drop("target", axis=1)

In [33]:
y = heart_disease["target"]

In [34]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [35]:
# split data into training and test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [36]:
# split data into training and test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [37]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((212, 13), (91, 13), (212,), (91,))

In [38]:
# 13 features / columns 
# 242 is from 303 samples and 80% is training so 303 x .8 = 242.4 
# Y has test set of 61, which is correct 242 + 61 = 303

## 1.1 make sure all car sales is numerical

In [39]:
car_sales = pd.read_csv("car-sales-extended.csv")
car_sales

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [40]:
len(car_sales)

1000

In [41]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [42]:
# Split into X / y
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

# Split into training and test

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [43]:
# Build marchine learning model
# Regression Model 
from sklearn.ensemble import RandomForestRegressor 

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'Toyota'

In [44]:
# Turn the categories into numbers 

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",
                                 one_hot, categorical_features)],
                               remainder="passthrough")

# covert into numbers
transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [45]:
X.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [46]:
## 12 is Odometer
# Make colours and door is someone between 0-11

pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [47]:
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [48]:
# Lets refit themodel

np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.3)
model.fit(X_train, y_train)
model.score(X_test, y_test)

# Basically it sucks .27 is horrible 

0.2764722437560483

## 1.2 How to fix the missing valuess?

1.  fill them with some values
2. remove the same with missing data altogether


In [49]:

# import car sale missing data

car_sale_missing = pd.read_csv("car-sales-extended-missing-data.csv")
car_sale_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [50]:
car_sale_missing.isna()
# is there any missing value 

Make  Colour  Odometer (KM)  Doors  Price
0    False   False          False  False  False
1    False   False          False  False  False
2    False   False          False  False  False
3    False   False          False  False  False
4    False   False          False  False  False
..     ...     ...            ...    ...    ...
995  False   False          False  False  False
996   True   False          False  False  False
997  False   False          False  False  False
998  False   False          False  False  False
999  False   False          False  False  False

[1000 rows x 5 columns]

In [51]:
car_sale_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [52]:
X = car_sale_missing.drop("Price", axis=1)
y = car_sale_missing["Price"]

In [53]:
# Lets try to convert our data to number 

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",
                                 one_hot, categorical_features)],
                               remainder="passthrough")

# covert into numbers
transformed_X = transformer.fit_transform(X)
transformed_X

ValueError: Input contains NaN

In [54]:
car_sale_missing.tail()

Make Colour  Odometer (KM)  Doors    Price
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

In [55]:
len(car_sale_missing)

1000

In [56]:
# Fill the "Make" column NaN with something

car_sale_missing["Make"].fillna("missing", inplace=True)

#Fill the colour column
car_sale_missing["Colour"].fillna("missing", inplace=True)

# fill the Odometer KM column
car_sale_missing["Odometer (KM)"].fillna(car_sale_missing["Odometer (KM)"].mean(), inplace=True)

# Fill the doors
car_sale_missing["Doors"].fillna(4, inplace=True)

In [57]:
car_sale_missing["Doors"].value_counts()
# average 4 doors

4.0    861
5.0     75
3.0     64
Name: Doors, dtype: int64

In [58]:
car_sale_missing

Make Colour  Odometer (KM)  Doors    Price
0      Honda  White        35431.0    4.0  15323.0
1        BMW   Blue       192714.0    5.0  19943.0
2      Honda  White        84714.0    4.0  28343.0
3     Toyota  White       154365.0    4.0  13434.0
4     Nissan   Blue       181577.0    3.0  14043.0
..       ...    ...            ...    ...      ...
995   Toyota  Black        35820.0    4.0  32042.0
996  missing  White       155144.0    3.0   5716.0
997   Nissan   Blue        66604.0    4.0  31570.0
998    Honda  White       215883.0    4.0   4001.0
999   Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [59]:
car_sale_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [60]:
# Remove rows with missing price values

car_sale_missing.dropna(inplace=True)

In [61]:
car_sale_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [62]:
len(car_sale_missing)

950

In [63]:
X = car_sale_missing.drop("Price", axis=1)
y = car_sale_missing["Price"]

In [64]:
# Lets try to convert our data to number 

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",
                                 one_hot, categorical_features)],
                               remainder="passthrough")

# covert into numbers
transformed_X = transformer.fit_transform(car_sale_missing)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

## Second method of fill missing data using Scikit-Learn

In [65]:
car_sale_missing = pd.read_csv("car-sales-extended-missing-data.csv")
car_sale_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [66]:
car_sale_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [67]:
# remove from dataframe 
car_sale_missing.dropna(subset=["Price"], inplace=True)
car_sale_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [68]:
#Split into X and y

X = car_sale_missing.drop("Price", axis=1)
y = car_sale_missing["Price"]

In [69]:
# Fill missing value with ScikitLearn 

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill categorical values with missing and numerical value with mean

cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

# define the column

cat_features = ["Make", "Colour"]
door_feature = ["Doors"]
num_features = ["Odometer (KM)"]

# Create an imputer (something that fills the missing data)
# this is the transformation occurs (takes a list and tuples)

imputer = ColumnTransformer([
    ("cat_imputer", cat_imputer, cat_features),
    ("door_imputer", door_imputer, door_feature),
    ("num_imputer", num_imputer, num_features)
])

# Transform the data
filled_X = imputer.fit_transform(X)
filled_X

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [70]:
car_sales_filled = pd.DataFrame(filled_X, columns=["Make", "Colour", "Doors", "Odometer (KM)"])
car_sales_filled.head()

Make Colour Doors Odometer (KM)
0   Honda  White     4         35431
1     BMW   Blue     5        192714
2   Honda  White     4         84714
3  Toyota  White     4        154365
4  Nissan   Blue     3        181577

In [71]:
car_sales_filled.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [72]:
# Lets try to convert our data to number 

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",
                                 one_hot, categorical_features)],
                               remainder="passthrough")

# covert into numbers # pass car sales filled 
transformed_X = transformer.fit_transform(car_sales_filled)
transformed_X

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [73]:
# Now we've got our data as numbers and filled (no missing values)
# lets fil a model 

np.random.seed(99)

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=.2)

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.11538315895283846

In [74]:
# Score is bad but it works. 
# Note to self, this clean up method is using sklearn build-in 

len(car_sales_filled), len(car_sales)

(950, 1000)

In [75]:
# 50 less sample drop score by A LOT and it was hard to find partterns. 
# Take away, clean data and lots of prep work.

## Choosing the right estimator / algo for our problem

Scikit Learn use estimator as another term for ML model or Algo

### 2.1 Picking a machine learning mode for a regression problem

In [76]:
# import boston housing data set

from sklearn.datasets import load_boston 
boston = load_boston()
boston;


In [77]:
# boston is dictioanry, now turn into dataframe

boston_df = pd.DataFrame(boston["data"], columns=boston["feature_names"])
boston_df["target"] = pd.Series(boston["target"])
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [78]:
len(boston_df)

506

In [79]:
# Use the scilearn cheat sheet to determine what model to use. 

# Lets use ridge regression model 

from sklearn.linear_model import Ridge
# Setup random seet

np.random.seed(99)

# Create the data
X = boston_df.drop("target", axis=1)
y = boston_df["target"]

# split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instantiate Ridge Model
model = Ridge()

# Check the score of the Ridge model on test data
model.fit(X_train, y_train)
model.score(X_test, y_test)

#0.65 is not bad but can be improved

0.6585594318027416

In [80]:
# Use random forest (my fav)

from sklearn.ensemble import RandomForestRegressor

# use random seed 99
np.random.seed(99)

# Create the data
X = boston_df.drop("target", axis=1)
y = boston_df["target"]

# split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instantiate Ridge Model
rf = RandomForestRegressor(n_estimators=100)

# Check the score of the Ridge model on test data
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

# This model is clearly better!

0.8252043655979256

In [81]:
# Ridge score 
model.score(X_test, y_test)

0.6585594318027416

In [82]:
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [83]:
len(heart_disease)

303

In [84]:
# Import the LinearSVC etimate class 

from sklearn.svm import LinearSVC

# setup random seed

np.random.seed(99)

# make the data

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# split the data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

# Instantiate LinearSVC

clf = LinearSVC(max_iter=100000)
clf.fit(X_test, y_test)

# Evalulate the LinearSVC score
clf.score(X_test, y_test)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


0.9016393442622951

In [85]:
# Import the RandomFores estimator class 

from sklearn.ensemble import RandomForestClassifier

# setup random seed

np.random.seed(99)

# make the data

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# split the data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

# Instantiate RandomFOrest

rfc = RandomForestClassifier(n_estimators=100)

# Check the score of the Ridge model on test data
rfc.fit(X_train, y_train)
rfc.score(X_test, y_test)

0.8524590163934426

## Notes 

Tidbit:
1. if you have structure data, use ensemble methods
2. if you have unstructured data, use deep learning or transfer learning

## 3. Fit the model/algo on our data and use to make predict

* x = feature, feautre variable, data
* y = labels, target, target variable


In [86]:
from sklearn.ensemble import RandomForestClassifier


# setup random seed
np.random.seed(99)



In [87]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [88]:
y.tail()

298    0
299    0
300    0
301    0
302    0
Name: target, dtype: int64

### 3.2 make predictions using a machine learning model 

2 ways to make prediction

1. predict()
2. predict_proba()

In [89]:
# use a trained model to make predictions

clf.predict(np.array([1,2,3,4,5,6]))

ValueError: Expected 2D array, got 1D array instead:
array=[1 2 3 4 5 6].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [90]:
X_test.head()

# prediction needs to be in this shape 

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
137   62    1   1       128   208    1        0      140      0      0.0   
262   53    1   0       123   282    0        1       95      1      2.0   
43    53    0   0       130   264    0        0      143      0      0.4   
90    48    1   2       124   255    1        1      175      0      0.0   
32    44    1   1       130   219    0        0      188      0      0.0   

     slope  ca  thal  
137      2   0     2  
262      1   2     3  
43       1   0     2  
90       2   2     2  
32       2   0     2

In [91]:
X_test.shape

(61, 13)

In [92]:
clf.predict(X_test)

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1])

In [93]:
np.array(y_test)

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1])

In [94]:
# Comapre predictions to truth labels to evalulate the model 

# Remember, y is the TRUTH 

y_preds = clf.predict(X_test)

# basically its comparing the two array and see if it did predict it correctly.
np.mean(y_preds == y_test)

0.9016393442622951

In [95]:
clf.score(X_test, y_test)
# same as above socre

0.9016393442622951

In [96]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.9016393442622951

# Make predictions with predict_proba()


In [97]:
# Predict_proba return probabilities of a classification label
clf.predict_proba(X_test[:5])

AttributeError: 'LinearSVC' object has no attribute 'predict_proba'

In [98]:
clf.predict(X_test[:5])

array([1, 0, 1, 1, 1])

### Note: So instead of return 1, 0, it shows the proability 

### Use predict() for regression models

In [99]:
# Import the RandomForest Regressor class 
from sklearn.ensemble import RandomForestRegressor

# setup random seed
np.random.seed(99)

# make the data
X = boston_df.drop("target", axis=1)
y = boston_df["target"]

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

# Instantiate RandomFOrestRegressor
rfc = RandomForestRegressor(n_estimators=100).fit(X_train, y_train)

# Make predictions
y_preds = model.predict(X_test)

In [100]:
y_preds[:10]

array([34.13206259, 34.72773759, 25.3959133 , 24.36379627, 34.76053791,
       19.84220506, -1.36909749, 16.3983325 , 20.01102328, 18.71600734])

In [101]:
np.array(y_test[:10])

array([35.4, 35.2, 24.8, 22.6, 34.9, 20. , 13.8, 19.4, 20.4, 20. ])

In [102]:
# Compare the predictions to the truth

from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

3.678681750869903

In [103]:
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [104]:
# On average, it predicts 3.67 away from the target

## 4. Evaluating a ML model

3 ways to eval sciitlearn model / estimators

1. esitmator "score" method
2. the scroing paramter
3. problem specific matrix function

### 4.1 Evaluating a mode with a score method 

In [105]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(99)

# make the data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# split the data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

# Instantiate RandomFOrest
rfc = RandomForestClassifier(n_estimators=100)

# Check the score of the Random Forest model on test data (Training machine learning model)
rfc.fit(X_train, y_train)


RandomForestClassifier()

In [106]:
rfc.score(X_train, y_train)
# returns the mean accuracy 
# 1 is TOO perfect and should be some red flag 

1.0

In [107]:
rfc.score(X_test, y_test)

0.8524590163934426

In [108]:
# Lets do the same but for regression 

In [113]:
# Import the RandomForest Regressor class 
from sklearn.ensemble import RandomForestRegressor

# setup random seed
np.random.seed(99)

# make the data
X = boston_df.drop("target", axis=1)
y = boston_df["target"]

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

# Instantiate RandomFOrestRegressor
rfc = RandomForestRegressor(n_estimators=100).fit(X_train, y_train)

# Get the score
rfc.score(X_test, y_test)

0.8252043655979256

In [114]:
# So in regression, the score is R^2, different than score from Classifier Score

In [116]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

cross_val_score(rfc, X_test, y_test, cv=5)

array([0.83405905, 0.70318006, 0.78038812, 0.75514094, 0.76096654])

In [117]:
# this cross validation score pretty much means split the data into chunks and get a score. 
# Cross is prefer because its more accurate and it trains on all the data instead of just .20 split and .8 train % of it
# Prevents lucky high score.  
cross_val_score(rfc, X_test, y_test, cv=10)


array([0.87117151, 0.82819514, 0.79563405, 0.76640797, 0.50618405,
       0.8957991 , 0.88048411, 0.60259478, 0.93043309, 0.31611419])

In [119]:
# Another Random Test on Cross Val Score

np.random.seed(99)

rfc_single_score = rfc.score(X_test, y_test)
rfc_cross_val_score = np.mean(cross_val_score(rfc, X, y, cv=5))
rfc_single_score, rfc_cross_val_score

(0.8252043655979256, 0.6239609759584595)

In [120]:
# Scroing paramter set to None by default

cross_val_score(rfc, X, y, cv=5, scoring=None)

array([0.77061251, 0.856968  , 0.73285833, 0.46447682, 0.31623059])

### 4.2.1 Classificiation model and evaluation metrics

1. accuracy
2. area under roc curve
3. confusion matrix
4. classification report

In [128]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

np.random.seed(99)

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

clf = RandomForestClassifier()
cross_val_score = cross_val_score(clf, X, y, cv=5)
cross_val_score

array([0.81967213, 0.8852459 , 0.78688525, 0.81666667, 0.78333333])

In [129]:
np.mean(cross_val_score)

0.8183606557377049

In [131]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [135]:
print(f"Heart Disease Classifer Cross Validated Accuracy: {np.mean(cross_val_score) * 100:.2f}%")

Heart Disease Classifer Cross Validated Accuracy: 81.84%


In [136]:
# basically its saying 81.84% the model will predict the right label given the data on heart disease. 

** Area under the reciver operating characteristic curve (AUC / ROC) **

* Area under durve AUC
* ROC Curve

ROC curves are a comparison of a model's ture postive rate (tpr) verus a model faluse positive rate (fpr)

* true positive = model predicts 1 when truth is 1
* false positive = model predicts 1 when truth is 0
* true negative = model predicts 0 when truth is 0
* false negative = model predits 0 when truth is 1

* basically baby statistic type 1 and type 2 error 

In [138]:
# Create X_test .... 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [139]:
from sklearn.metrics import roc_curve

# fit the classifer
clf.fit(X_train, y_train)

# make prediction with probabilities 
y_probs = clf.predict_proba(X_test)
y_probs[:10], len(y_probs)

(array([[0.18, 0.82],
        [0.1 , 0.9 ],
        [0.  , 1.  ],
        [0.74, 0.26],
        [0.79, 0.21],
        [0.14, 0.86],
        [0.14, 0.86],
        [0.17, 0.83],
        [0.05, 0.95],
        [0.21, 0.79]]),
 61)

In [140]:
y_probs_positive = y_probs[:,1]
y_probs_positive[:10]

array([0.82, 0.9 , 1.  , 0.26, 0.21, 0.86, 0.86, 0.83, 0.95, 0.79])